### ISSUE TITLE
Second consecutive ad is unmuted.

### ISSUE THREAD

**Issue by jaybourn** [SecUpwN/Spotify-AdKiller#28] opened 2015-03-17 13:04 UTC
If two ads are played in a row, Spotify is unmuted for the second ad. I start spotify by using the spotify-wrapper.sh script.

Ubuntu 14.04
Spotify 0.9.11.27.g2b1a638c
Lastest master version of adkiller.

Config:
```
CUSTOM_MODE="simple"
CUSTOM_PLAYER=""
CUSTOM_LOOPOPT=""
CUSTOM_VOLUME=""
CUSTOM_MUSIC=""
CUSTOM_ALERT=""
DEBUG="0"
```

Example output:
```
XPROP:    Spotify - Avicii – Hey Brother
DBUS:     Hey Brother
PAUSED:   No
AD:       No
LOCAL:    No
## Initial run ##
## Unmuting sink 1170 ##
------------------------------------------------------------------------------
XPROP:    Spotify - Royal Navy – Made In The
DBUS:     Hey Brother
PAUSED:   No
AD:       Yes
LOCAL:    No
## Muting sink 1170 ##
------------------------------------------------------------------------------
XPROP:    Spotify - Xlite – Swatch
DBUS:     Hey Brother
PAUSED:   No
AD:       Yes
LOCAL:    No
## Restoring state ##
## Unmuting sink 1170 ##
```

**Comment by Feltzer** [comment] 2015-03-17 16:45
Hi. Thanks for the bug report. To track this down we will need to dig a little deeper into the logs. Could you please set `DEBUG` to `1` in the config file and try to reproduce the bug? As soon as you've got it please post the log excerpt here.

**Comment by SecUpwN** [comment] 2015-03-17 16:49
Whoa, I', amazed at how fast you are tackling all these things @Feltzer. So happy to have you here, man! Let me know if there's anything good I can do for you to show you my appreciation of your work!

**Comment by Feltzer** [comment] 2015-03-17 17:08
@SecUpwN Thanks for the kind words :). Honestly, I am just happy to help, but I appreciate the sentiment!

@jaybourn Actually, scratch what I said in my last post. Please give the latest master branch a try. I think the issue should be fixed now.

**Comment by Feltzer** [comment] 2015-03-17 17:10
No idea why, but my commit closed this issue automatically. Sorry about that.

**Comment by SecUpwN** [comment] 2015-03-17 21:49
@Feltzer, that's not a bug, it's a feature: If you commit with `fix #28`, GitHub closes it as fixed.

**Comment by Feltzer** [comment] 2015-03-18 12:12
@SecUpwN Interesting! Somehow I never noticed that.

**Comment by jaybourn** [comment] 2015-03-18 16:46
@Feltzer The issue seems to be fixed with your last commit. Thanks for doing it so promptly and keep up the good work!

**Closed** 2015-03-18 19:46 UTC
Labels: BUG

**Comment by Feltzer** [comment] 2015-03-18 21:25
@jaybourn Awesome. That's great to hear :).
