### ISSUE TITLE
wmctrl: missing dependencies

### ISSUE THREAD

**Issue by Nhoya** [SecUpwN/Spotify-AdKiller#40] opened 2015-12-03 17:16 UTC
Hey there, at line 562 of `spotify-adkiller.sh`:
```
done < <(xprop -spy -id $(wmctrl -lx | awk -F' ' '$3 == "spotify.Spotify" {print $1}') _NET_WM_NAME)
```
wmctrl is not a default utility so please add it to dependecies list  ty :+1:

**Comment by SecUpwN** [comment] 2015-12-03 18:52
Good evening @Nhoya, is this actually a dupe of #39? I'll add the dependency soon, stay tuned.

**Closed** 2015-12-03 18:59 UTC
Labels: DUPLICATE, ENHANCEMENT
