### ISSUE TITLE
How to fix rare instances of ads not being muted

### ISSUE THREAD

**Issue by quietoparado** [SecUpwN/Spotify-AdKiller#26] opened 2015-02-27 20:38 UTC
Hi! thanks for this script, it works really fine but some rare ads has a DBUS empty value and I have changed the script for remove it.

**RARE ADS**

    -----------------------------------------
    XPROP:    Spotify - Spotify – Spotify
    DBUS:     
    PAUSED:   No
    AD:       No
    LOCAL:    No
    ## Regular track ##
    DBUSOUTPUT : method return sender=:1.9904 -> dest=:1.12729 reply_serial=2
       array [
       ]
    ---------------------------------------
    XPROP: Spotify
    DBUS:
    PAUSED: Yes # <<<<<<< NOT PAUSED. IS AN AD, THE DBUS VALUE IS EMPTY.
    AD: No
    LOCAL: No
    ## Paused by User ##
    DBUSOUTPUT : method return sender=:1.9904 -> dest=:1.12729 reply_serial=2
       array [
       ]
    ---------------------------------------

Yesterday I detect the rare tracks of the issue  "Some ads are not being muted #13 "

https://github.com/SecUpwN/Spotify-AdKiller/issues/13

I add this condition to the script and now works fine for me.

On another topic. In the script I found this code:

    # get track data from xprop and the DBUS interface
    XPROP_TRACKDATA="$(echo "$XPROPOUTPUT" | cut -d\" -f 2- | rev | cut -d\" -f 2- | rev)"
    DBUS_TRACKDATA="$(echo "$DBUSOUTPUT" | grep xesam:title -A 1 | grep variant | \
    cut -d\" -f 2- | rev | cut -d\" -f 2- | rev)"
    # `cut | rev | cut | rev` gets string between first and last double-quotes
    # TODO: find a more elegant way to do this

I think the more simple mode of obtain the XPROP_TRACKDATA and DBUS_TRACKDATA variables is:

    XPROP_TRACKDATA="$(echo "$XPROPOUTPUT" | cut -d\" -f 2)"
    DBUS_TRACKDATA="$(echo "$DBUSOUTPUT" | grep xesam:title -A 1 | grep variant | cut -d\" -f 2)"

You can see these changes in my fork and include it in the master branch if you like it.

https://github.com/quietoparado/Spotify-AdKiller/commit/38e2f12bb187f5e8f8746f69278e0cde5d9a7c05

**Comment by Feltzer** [comment] 2015-02-28 04:38
Hi,

first of all thanks for your feedback! We are always happy about new contributions.

>Yesterday I detect the rare tracks of the issue "Some ads are not being muted #13 "

> I add this condition to the script and now works fine for me.

Awesome. Never having experienced this type of bug myself I am glad that you were able to track it down. I will give your condition checks a try and see if they work fine here. If they do I will add them to the testing branch, so more people can test them out.

> On another topic. In the script I found this code: [...]

> I think the more simple mode of obtain the XPROP_TRACKDATA and DBUS_TRACKDATA variables is [...]

The reason that `cut | rev | cut | rev` sequence is necessary is because both the XPROP and DBUS output can include double-quotes. If we only use one `"`-delimited `cut`  we can end up with truncated data.

Anyway, thanks again for helping out! I will review your changes over the next couple of days.

**Comment by Feltzer** [comment] 2015-02-28 06:04
OK, seeing how I have never been able to reproduce this issue on my system I'd really appreciate it if you could post or link a couple more excerpts of your debug logs where you think the unmuted ads appear. And, for comparison's sake, it would also be good to have a couple log excerpts where everything is working fine.

Also, it looks like you printed `$DBUSOUTPUT` manually by modifying the script. There's no need for that. Please just set `DEBUG` to `1` in your config file (`$HOME/.Spotify-AdKiller.log`). This will automatically print DEBUG messages for dbus, xprop, and a lot of other stuff. If you can, try to replicate the bug with the unmodified version of the script (i.e. the `master` branch) while the DEBUG mode is active, and post the logs here.

**Comment by quietoparado** [comment] 2015-02-28 10:01
Thanks for yours coments, I go to try the master script whit DEBUG=1 and see if I can reproduce the problem, but the results of the DEBUG will be the same as printing the variable manually, I also have printed without changing the master script. The problem is that these tracks with announcement has variable DBUSOUTPUT as shown:

DBUSOUTPUT : method return sender=:1.9904 -> dest=:1.12729 reply_serial=2
   array [
   ]

The DBUS_TRACKDATA is an empty value, in this case:

DBUS_TRACKDATA="$(echo "$DBUSOUTPUT" | grep xesam:title -A 1 | grep variant | \
cut -d\" -f 2- | rev | cut -d\" -f 2- | rev)"

The array of DBUSOUTPUT is empty and there is nothing to do grep, then the variable DBUS_TRACKDATA is empty. The master script with this condition makes bad decisions, is not ready for that.

XPROP:    Spotify - Spotify – Spotify
DBUS:     
PAUSED:   No
AD:       No
LOCAL:    No
## Regular track ##

XPROP:    Spotify
DBUS:     
PAUSED:   Yes
AD:       No
LOCAL:    No
## Paused by User ##

In a normal ad, the variable DBUS_TRACKDATA is not empty and the master script makes decisions correctly.

XPROP_DEBUG: WM_ICON_NAME(COMPOUND_TEXT) = "Spotify - Spotify – SFDK"
DBUS_DEBUG:  method return sender=:1.13920 -> dest=:1.13965 reply_serial=2
   array [
      dict entry(
         string "mpris:artUrl"
         variant             string "http://open.spotify.com/thumb/bffc944b4fb7e6309cb2c348cebe2a6b363f9cbe"
      )
      dict entry(
         string "mpris:length"
         variant             uint64 193000000
      )
      dict entry(
         string "mpris:trackid"
         variant             string "spotify:track:2v96emmdlfM0hx8RuuLU3o"
      )
      dict entry(
         string "xesam:album"
         variant             string "Burning for No One"
      )
      dict entry(
         string "xesam:artist"
         variant             array [
               string "The Cribs"
            ]
      )
      dict entry(
         string "xesam:autoRating"
         variant             double 0.42
      )
      dict entry(
         string "xesam:contentCreated"
         variant             string "2015-01-01T00:00:00"
      )
      dict entry(
         string "xesam:discNumber"
         variant             int32 0
      )
      dict entry(
         string "xesam:title"
         variant             string "Burning for No One"
      )
      dict entry(
         string "xesam:trackNumber"
         variant             int32 1
      )
      dict entry(
         string "xesam:url"
         variant             string "spotify:track:2v96emmdlfM0hx8RuuLU3o"
      )
   ]
XPROP:    Spotify - Spotify – SFDK
DBUS:     Burning for No One
PAUSED:   No
AD:       Yes
LOCAL:    No
admute: 0; pausesignal: 0; adfinished: 0
pactl: mute
## Muting sink 48 ##

If he reason that cut | rev | cut | rev sequence is necessary because both the XPROP and DBUS output can include double-quotes, then the "sed" command can make a great job. Using sed as show below, the variables can have multiple quotes, not only double-quotes, and be recognized correctly:

XPROP_TRACKDATA="$(echo "$XPROPOUTPUT" | cut -d\" -f 2- | sed 's/"$//g')"
DBUS_TRACKDATA="$(echo "$DBUSOUTPUT" | grep xesam:title -A 1 | grep variant  | cut -d\" -f 2- | sed 's/"$//g')"

**Comment by Feltzer** [comment] 2015-02-28 11:05
> If he reason that cut | rev | cut | rev sequence is necessary because both the XPROP and DBUS output can include double-quotes, then the "sed" command can make a great job. Using "sed" as show below, the variables can have multiple quotes, not only double-quotes, and be recognized correctly: [...]

That's far more elegant than what we had before. Thanks! I added it to the testing branch (7ae93cd068844b558e4fa018784290858aea95d6).

> [...]

> The array of DBUSOUTPUT is empty and there is nothing to do grep, then the variable DBUS_TRACKDATA is empty. The master script with this condition makes bad decisions, is not ready for that.

> [...]

> In a normal ad, the variable DBUS_TRACKDATA is not empty and the master script makes decisions correctly.

> [...]

> In a normal pause, the variable DBUS_TRACKDATA is not empty, and the master script makes decisions correctly, but in the ad with "XPROP: Spotify" and the DBUS empty, the master script fail.

Thanks for the explanation. I see what you mean now. 

77a0253a1c6ce6b5496b812aa31295b6bf067a42 implements the changes you suggested. I slightly modified your syntax to be more consistent with the rest of the script, but the logic should be the same. If you can, please give the [testing branch](https://github.com/SecUpwN/Spotify-AdKiller/tree/testing) a try to see if everything works as expected.

As far as the logs are concerned, I don't think we need them anymore.

**Comment by SecUpwN** [comment] 2015-03-01 17:49
@quietoparado,thank you for your awesome contribution! @Feltzer, when to merge?

**Comment by Feltzer** [comment] 2015-03-02 07:18
As soon as we get some more testing done. The most important thing right now is to ensure that the changes to the ad detection logic don't result in some unforeseen regressions. That's why I would encourage everyone willing to help to switch to the testing branch and try it out for a few days. After that we can merge everything into the master branch.

The next step would be to check whether the latest changes actually fix the issues described in #24 and #26; but because both of these bugs are very rare this could take a while.

**Comment by Feltzer** [comment] 2015-03-04 10:15
@quietoparado 

I am sorry, but it looks like the empty DBUS output is not a reliable indicator of ads being on. Over the past few days I've discovered multiple instances where the AdKiller would trigger falsely and mute regular tracks. I have managed to squash one type of these false positives with c557d238e825de8adba7ba79a3bb18121a3b3f54, but that only applies to the issues experienced at startup. 

Far more problematic is the fact that with these latest changes to the ad detection logic Spotify AdKiller will trigger a mute whenever a user plays any of the recommended tracks on the 'Discover' page. To reproduce this issue make sure Spotify and the testing branch AdKiller are up and running, then click on 'Discover' in the left sidebar and hit play on any of the recommendations visible. 

Going through the logs I've found that this happens because Spotify will briefly return an empty DBUS output when triggering playback on these recommended songs, e.g.:

    ---------------------------------------------------------------------------------------------------------
    XPROP_DEBUG: WM_ICON_NAME(STRING) = "Spotify"
    DBUS_DEBUG:  method return sender=:1.2881 -> dest=:1.3132 reply_serial=2
       array [
       ]
    XPROP:    Spotify
    DBUS:     
    PAUSED:   No
    AD:       Yes
    LOCAL:    No
    admute: 0; pausesignal: 0; adfinished: 0
    ## Switching to local playback ##
    pactl: mute
    ## Muting sink 24 ##
    ---------------------------------------------------------------------------------------------------------
    XPROP_DEBUG: WM_ICON_NAME(COMPOUND_TEXT) = "Spotify - Lou Reed – Walk on the Wild Side"
    DBUS_DEBUG:  method return sender=:1.2881 -> dest=:1.3134 reply_serial=2
       array [
          dict entry(
             string "mpris:artUrl"
             variant             string "http://open.spotify.com/thumb/b0c230b7a0a61b6a53721321f13129245016e24b"
          )
          dict entry(
             string "mpris:length"
             variant             uint64 252000000
          )
          dict entry(
             string "mpris:trackid"
             variant             string "spotify:track:3Y4BV4pDRfohB1LYAA5W7Y"
          )
          dict entry(
             string "xesam:album"
             variant             string "Discover Lou Reed"
          )
          dict entry(
             string "xesam:artist"
             variant             array [
                   string "Lou Reed"
                ]
          )
          dict entry(
             string "xesam:autoRating"
             variant             double 0.32
          )
          dict entry(
             string "xesam:contentCreated"
             variant             string "2007-01-01T00:00:00"
          )
          dict entry(
             string "xesam:discNumber"
             variant             int32 1
          )
          dict entry(
             string "xesam:title"
             variant             string "Walk on the Wild Side"
          )
          dict entry(
             string "xesam:trackNumber"
             variant             int32 1
          )
          dict entry(
             string "xesam:url"
             variant             string "spotify:track:3Y4BV4pDRfohB1LYAA5W7Y"
          )
       ]
    XPROP:    Spotify - Lou Reed – Walk on the Wild Side
    DBUS:     Walk on the Wild Side
    PAUSED:   No
    AD:       No
    LOCAL:    Yes
    admute: 1; pausesignal: 0; adfinished: 0
    ## Pausing Spotify until local playback finished / user interrupt ##
    dbus: Pause

Unfortunately I can't think of any way to distinguish between empty DBUS outputs due to ads and due to any other reason. To me it looks like we will have to choose between ignoring the rare instances of false negatives described in this bug report or ignoring the false positives mentioned above. And seeing how these false positives are pretty severe, I would argue against merging the modified ad detection logic into the `master` branch; at least until we find a way to avoid false negatives without causing false positives in the process.

**Comment by quietoparado** [comment] 2015-03-04 15:13
Clearly there are more disadvantages than advantages to detect empty DBUS like an advertisement. I use Spotify version 0.9.4.183 and Discover does not work, why had not detected the error by introducing the logic of empty DBUS equal to ad. I believe that although some announcements are heard, we should not lose functionality in the Discover page. Thank you for your interest in solving this problem.

**Comment by Feltzer** [comment] 2015-03-06 07:34
@quietoparado Yeah, the experience with older Spotify clients definitely varies. We should probably add a note on this to the documentation.Thanks again for all your help and input! 

I have reverted the changes to the ad detection logic for the time being and merged the testing branch into main. I will leave this issue open as we haven't managed to find a solution, yet. If anyone has any ideas how to address these instances of false negatives please feel free to chime in!

**Comment by SecUpwN** [comment] 2015-03-20 03:01
> If anyone has any ideas how to address these instances of false negatives please feel free to chime in!

Maybe @OlegSmelov's smart brain has some ideas on how to tackle this?

**Comment by SecUpwN** [comment] 2015-06-13 17:20
>If anyone has any ideas how to address these instances of false negatives please feel free to chime in!

Without being pushy, are there any news on this Issue yet?

**Comment by Feltzer** [comment] 2015-06-19 10:25
@SecUpwN Nope, nothing comes to mind, yet. Sorry.

**Comment by SecUpwN** [comment] 2015-11-16 00:21
>Nope, nothing comes to mind, yet. Sorry.

Maybe @itsamenathan has an idea about this?

**Comment by kriswebdev** [comment] 2015-12-27 19:39
Not related to empty DBUS, but I get those tracks not muted on Spotify 1.0.19.106 (they are not paused by the way):

```
XPROP:    Spotify
DBUS:      - Spotify
PAUSED:   Yes
AD:       Can't say
LOCAL:    No
## Paused by User ##
```

**Comment by Feltzer** [comment] 2016-01-03 06:48
@kriswebdev This is a actually a new bug that has become evident with Spotify 1.x. 

We used to be able to tell whether a track or ad was paused by looking at the xprop output. If it only read `Spotify` that would indicate a playback pause.

The same output is much more ambiguous with Spotify 1.x. As we rely on being able to tell whether a track is paused or not in order to control interluded local music, fixing this will be quite difficult. At the moment I am still waiting for the Spotify team to complete the integration of DBUS into the beta, so that the `PlaybackStatus` property can be read directly from the DBUS interface.

**Comment by Feltzer** [comment] 2016-01-03 15:36
@kriswebdev The latest commit should fix your issue. 

As for the other instances of unmuted ads experienced with Spotify 0.9.x, the latest update might improve the situation somewhat.

**Comment by Feltzer** [comment] 2016-01-12 17:26
Seeing how I have yet to run into an umuted ad with the latest release of the script, I will close this issue for now. If any of you guys experience this again please feel free to post here and I'll reopen the issue.

**Closed by Feltzer** 2016-01-12 17:26 UTC
Labels: BUG, HELP_WANTED
