### ISSUE TITLE
Stopped working with new version of Spotify

### ISSUE THREAD

**Issue by kodzak** [SecUpwN/Spotify-AdKiller#50] opened 2016-03-03 13:24 UTC
Adds aren't blocked. Changing name from "Spotify Free - Linux Preview" on "Spotify" in config file(spotify-adkiller.sh) nothing change. Adds still are played.

**Comment by OlegSmelov** [comment] 2016-03-04 09:32
Just tested Spotify 1.0.23.93 on Ubuntu 15.04 and it worked.

@kodzak Can you provide more information? Distro, exact Spotify version, logs, ...

**Comment by kodzak** [comment] 2016-03-05 10:06
I use elementary Os Freya it is based on Ubuntu 14.04. Spotify version 1.0.23.93.gd6cfae15.
Script mute adds only if i pause and play again. Not mute adds automatically. I download again this script and still this happened.

**Comment by billpcs** [comment] 2016-03-05 22:08
Can confirm the exact same behaviour on the exact same system.

System: elementary OS Freya x86_64
Spotify version 1.0.23.93.gd6cfae15

**Comment by RaphaBarros** [comment] 2016-03-06 16:26
Ubuntu 14.04 and I can confirm the same problem.

**Comment by bacci85** [comment] 2016-03-10 08:59
Here is what happens to me:

```
$ spotify-wrapper.sh 
## Waiting for Spotify ##
## Waiting for Spotify ##
## Waiting for Spotify ##
## Waiting for Spotify ##
## Waiting for Spotify ##
## Waiting for Spotify ##
## Waiting for Spotify ##
## Waiting for Spotify ##
## Waiting for Spotify ##
## Waiting for Spotify ##
Error: Spotify not found.

```

Spotify opens automatically after spotify-wrapper.sh is called, but on the shell it seems it does not recognize that the program is executing...

**Comment by rjd22** [comment] 2016-03-10 15:40
I have the same problem the problem I'm having is that spotify creates multiple audio sinks and plays in a different audio sink than the blocker blocks.

So ads keep playing while the blocker blocks the wrong audio sink. I changed the blocker to block both audio sinks and now it's working but nothing keeps spotify to open 3 sinks to work around this problem.

**Comment by SecUpwN** [comment] 2016-03-11 11:35
Sorry folks that you're having so many troubly with it currently. @Feltzer, can you digg into this, please?

**Comment by mad73923** [comment] 2016-03-12 13:32
Seems like the new version doesn't publish the current title to the system media control. Every new title I get a desktop notification with the title, but the album cover and other info isn't shown in the systems media box anymore. Any fix for this?
Linux Mint 17.3
Spotify 1.0.24.104.g92a22684

**Comment by Micr0Bit** [comment] 2016-03-14 12:07
i can confirm this bug ... on 
Debian GNU/Linux 8.3 (jessie)

the adkiller works sometimes ... but not always (since the new spotify version)

**Comment by rjd22** [comment] 2016-03-17 14:39
I can confirm what @Micr0Bit  says. It stopped detecting ads correctly. Only after I pause and play again it is able to see that it's an ad running.

**Closed** 2016-03-19 14:53 UTC
Labels: BUG, DUPLICATE
