### ISSUE TITLE
Not working on Spotify 0.9.17.g9b85d436?

### ISSUE THREAD

**Issue by x-ji** [SecUpwN/Spotify-AdKiller#42] opened 2015-12-08 13:11 UTC
The README file specified version 0.9.11. However when I installed the official version of Spotify on Ubuntu yesterday, the version was already `0.9.17.g9b85d436`. The script seems to be not working. Is this version not supported indeed? If so, is it possible for me to install 0.9.11 instead of 0.9.17.

**Comment by Feltzer** [comment] 2015-12-08 21:25
This is a duplicate of #37.

**Closed by Feltzer** 2015-12-08 21:25 UTC
Labels: DUPLICATE
