### ISSUE TITLE
question: is this a suitable solution for the muting problem?

### ISSUE THREAD

**Issue by rhoconlinux** [SecUpwN/Spotify-AdKiller#24] opened 2015-02-14 13:12 UTC
I'm having a recurrent muting of spotify after the adds blocking. As you mention in the readme, it is solved by running one simple line. I try it manually and works like a charm... but I have to confess that it is a bit annoying :) So, since I'm using the simple blocking mode (in other words, just mute spotify  during the add), I am currently trying this modded version of the adkiller script:

in line 428 of the script I added the "forced unmuting" after the <code>fi</code> and before the closing of the function, like this:

<code>
    fi

<b> <pre>for i in $(LC_ALL=C pactl list | grep -E '(^Sink Input)|(media.name = \"Spotify\"$)' | cut -d \\# -f2 | grep -v Spotify); do pactl set-sink-input-mute "$i" no; done</b></pre>

<code>}
</code>  

...Until now seems to be working, but  I don't have the programming skills I don't know if what I did make sense. ^_^

Anyway, obviously it is only feasible on the <code>automute_simple</code> mode, but could be a workaround to avoid spotify to stop playing after blocking. Right?

Cheers!!! :+1:

**Comment by Feltzer** [comment] 2015-02-14 15:54
Hi again and thanks for the bug report!

I must admit that I've been experiencing the same issue for a while now, but I haven't had the time to track it down properly, yet. I'll do some debugging over the next few days and try out some solutions including yours :).

**Comment by SecUpwN** [comment] 2015-02-26 10:20
Good morning @Feltzer, what's the current status of this?

**Comment by Feltzer** [comment] 2015-02-26 14:16
Hi, sorry for the delay. 

This is a somewhat tricky problem to tackle because the bug is hard to reproduce. I am still not quite sure under which circumstances the unmuting fails. I am experimenting with a few code changes based on @rhoconlinux's idea, but I can't say for sure if they are working. See, ever since I introduced these changes on my local branch I haven't experienced this bug, but because this issue was very rare in the first place I can't confidently say that it's actually fixed. 

I think I might create a testing branch later today and push my version for you guys to test it. The more eyes we get on this, the easier it will be to track this bug down.

**Comment by Feltzer** [comment] 2015-02-26 14:43
Alright, there we go. The [testing](https://github.com/SecUpwN/Spotify-AdKiller/tree/testing) branch is up. I'd appreciate it if you guys gave it a try. Let's see if it fixes this issue.

**Comment by rhoconlinux** [comment] 2015-02-26 15:43
awesome, will try it now. By the way, the first attempt I posted above didn't solved the issue, however in order to be exhaustive (and most likely redundant) I added the same line in several places, specially in the unmute definition and and after every time the unmute function was called. Seems to work, but as you say is really a "hunch" because I don't know how to test it. ^_^
Cheers!

**Comment by Feltzer** [comment] 2015-03-04 10:20
@rhoconlinux 

Hi there,

just wondering how the testing is going. Have you experienced any mutes of this type since switching to the testing branch?

**Comment by rhoconlinux** [comment] 2015-03-04 19:42
Indeed I experienced a major issue due to the systematic fail in blocking. But no drama with the muting till now.

**Comment by Feltzer** [comment] 2015-03-06 07:38
@rhoconlinux: Thanks for the feedback! I have reverted the changes in the testing branch that were causing the regressions in ad detection and merged the commits related to the muting problem into the master branch. I'd really appreciate it if you could give the latest master branch a try to see if everything works fine for you.

**Comment by SecUpwN** [comment] 2015-04-18 17:15
Any news on the testing with our `master` branch, @rhoconlinux?

**Comment by rhoconlinux** [comment] 2015-04-23 15:01
It's been working flawlessly :)
Thanks a lot!

**Comment by SecUpwN** [comment] 2015-04-24 04:31
>It is working flawlessly :)

Makes me very happy to hear! @Feltzer, send me your postal address via mail to get a German beer!

**Closed by SecUpwN** 2015-04-24 04:31 UTC
Labels: BUG

**Comment by OlegSmelov** [comment] 2015-04-24 07:50
@SecUpwN is tricking @Feltzer into giving away his postal address :trollface:

**Comment by SecUpwN** [comment] 2015-04-24 08:31
>@SecUpwN is tricking @Feltzer into giving away his postal address :trollface:

Of course! I will have a massive cum party at his house.. with **YOU**, @OlegSmelov! :tada:

**Comment by Feltzer** [comment] 2015-05-01 09:16
@rhoconlinux Awesome. Glad to hear that!

@SecUpwN Not that big on beer myself, but I appreciate the gesture! Also, @OlegSmelov makes a good point: [How do I know you're not the NSA](https://i.imgur.com/wJfihlm.jpg)?
